language: node_js
dist: trusty
node_js:
  - 6
  - 8
script:
  - node --version
  - npm install
  - npm run lint:ts
  - npm run lint:css
  - npm run build
notifications:
    email:
      on_failure: change
cache:
  npm: true
  directories:
    - node_modules
