language: node_js
dist: trusty
node_js:
  - 6
  - 8
script:
  - node --version
  - yarn
  - yarn run lint:ts
  - yarn run lint:css
  - yarn run build
  - yarn run test
notifications:
    email:
      on_failure: change
cache:
  yarn: true
  directories:
    - node_modules

 notifications:
  slack:
    rooms:
      - superhotfire:vXdoFnSafk36YUfPZC791wZh#project-feed
